version: '3'
services:
  createuser:
    image: createuser
    build:
      context: FileStorage
      dockerfile: Dockerfile
    depends_on:
      minio1:
        condition: service_started
      minio2:
        condition: service_started
      minio3:
        condition: service_started
      minio4:
        condition: service_started
    command: ["./createuser.sh", "http://minio1:9000"]
    volumes:
      - .env:/usr/local/bin/.env
    env_file:
      - .env

  minio1:
    image: minio/minio
    volumes:
      - minio1-data:/data
    ports:
      - "9001:${PORT_MINIO}"
      - "9091:9091"
    env_file:
      - .env
    command: server --console-address ":9091" http://minio{1...4}/data

  minio2:
    image: minio/minio
    volumes:
      - minio2-data:/data
    ports:
      - "9002:${PORT_MINIO}"
      - "9092:9092"
    env_file:
      - .env
    command: server --console-address ":9092" http://minio{1...4}/data

  minio3:
    image: minio/minio
    volumes:
      - minio3-data:/data
    ports:
      - "9003:${PORT_MINIO}"
      - "9093:9093"
    env_file:
      - .env
    command: server --console-address ":9093" http://minio{1...4}/data

  minio4:
    image: minio/minio
    volumes:
      - minio4-data:/data
    ports:
      - "9004:${PORT_MINIO}"
      - "9094:9094"
    env_file:
      - .env
    command: server --console-address ":9094" http://minio{1...4}/data

  serverfastify:
    image: serverfastify
    build: ServerFastify
    env_file:
      - .env
    expose:
      - "${PORT_SERVERFASTIFY}"
    depends_on:
        - broker

  reactapp:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: reactapp
    container_name: filenest-client
    ports:
      - "3001:${PORT_REACTAPP}" # runs on port 3001

  broker:
    image: broker
    build: 
      context: ./Broker
      dockerfile: Dockerfile
    env_file:
      - .env

  nginx:
    image: nginx-server
    build: 
      context: ./Nginx
      dockerfile: Dockerfile
    container_name: nginx
    env_file:
      - .env
    depends_on:
      serverfastify:
        condition: service_started
      reactapp:
        condition: service_started
      broker:
        condition: service_started
      servermetadb:
        condition: service_started
    ports:
      - "${PORT_NGINX}:${PORT_NGINX}"

  metadb:
    image: metadb
    build: MetaDB
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - .env:/usr/local/bin/.env
      - /var/lib/mysql
    ports:
      - "9000-9100:${PORT_METADB}"
    depends_on:
      - broker

  servermetadb:
    image: servermetadb
    build: ./MetaDBServer
    depends_on:
      - metadb
      - broker
    env_file:
      - .env
    environment:
      - MYSQL_HOST=metadb
    expose:
      - "${PORT_SERVERMETADB}"

  admin:
    image: admin
    build: ./Admin
    env_file:
      - .env
    depends_on:
      - broker
      - metadb
      - servermetadb
    ports:
      - "3000:${PORT_ADMIN}"

volumes:
  minio1-data:
  minio2-data:
  minio3-data:
  minio4-data:
  metadb-data:
    driver: local