version: '3'
services:
  broker1:
    build: .
    container_name: broker1
    ports:
      - "6001:6001"
    networks:
      - sockets
  broker2:
    build: .
    container_name: broker2
    environment:
      - url1=ws://broker1:6001
    ports:
      - "6002:6001"
    networks:
      - sockets
    depends_on:
      - broker1

  broker3:
    build: .
    container_name: broker3
    environment:
      - url1=ws://broker1:6001
      - url2=ws://broker2:6001
    ports:
      - "6003:6001"
    networks:
      - sockets
    depends_on:
      - broker2

  broker4:
    build: .
    container_name: broker4
    ports:
      - "6004:6001"
    networks:
      - sockets
    depends_on:
      - broker3

networks:
  sockets:
    driver: bridge