version: '3'
services:
  createuser:
    build: .
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    command: ["./createuser.sh", "http://minio1:9000"]
    volumes:
      - .env:/usr/local/bin/.env
    env_file:
      - .env
    networks:
      - minio_network
    restart: "no" 
  minio1:
    image: minio/minio
    volumes:
      - minio1-data:/data
    ports:
      - "9001:9000"
      - "9091:9091"
    env_file:
      - .env
    command: server --console-address ":9091" http://minio{1...4}/data
    networks:
      - minio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio
    volumes:
      - minio2-data:/data
    ports:
      - "9002:9000"
      - "9092:9092"
    env_file:
      - .env
    command: server --console-address ":9092" http://minio{1...4}/data
    networks:
      - minio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio
    volumes:
      - minio3-data:/data
    ports:
      - "9003:9000"
      - "9093:9093"
    env_file:
      - .env
    command: server --console-address ":9093" http://minio{1...4}/data
    networks:
      - minio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  
  minio4:
    image: minio/minio
    volumes:
      - minio4-data:/data
    ports:
      - "9004:9000"
      - "9094:9094"
    env_file:
      - .env
    command: server --console-address ":9094" http://minio{1...4}/data
    networks:
      - minio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio1-data:
  minio2-data:
  minio3-data:
  minio4-data:

networks:
  minio_network:
    name: minio_network
    driver: bridge